name: Package Executable

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build-macos-11:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew install gettext
          echo "export PATH=\"/usr/local/opt/gettext/bin:$PATH\"" >> ~/.zshrc
          echo "export DYLD_LIBRARY_PATH=\"/usr/local/opt/gettext/lib:$DYLD_LIBRARY_PATH\"" >> ~/.zshrc
          source ~/.zshrc
          echo "Dependencies installed."

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'

      - name: Pip Install
        run: python -m pip install --upgrade pip

      - name: Poetry Install
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true --local
          poetry install

      - name: Install Pyinstaller
        run: poetry add pyinstaller

      - name: Create Executable File (macOS 11)
        run: poetry run pyinstaller -F "main.py" --clean --dist ./out --name "CxKitty" --add-data ".venv/lib/python3.10/site-packages/ddddocr/common.onnx:ddddocr" --add-data ".venv/lib/python3.10/site-packages/ddddocr/common_det.onnx:ddddocr" --add-data ".venv/lib/python3.10/site-packages/ddddocr/common_old.onnx:ddddocr"

      - name: Copy Required Files
        run: |
          cp config.yml out/
          cp pyproject.toml out/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: CxKitty For macOS 11
          path: |
            out

  build-macos-12:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew install gettext
          echo "export PATH=\"/usr/local/opt/gettext/bin:$PATH\"" >> ~/.zshrc
          echo "export DYLD_LIBRARY_PATH=\"/usr/local/opt/gettext/lib:$DYLD_LIBRARY_PATH\"" >> ~/.zshrc
          source ~/.zshrc
          echo "Dependencies installed."

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'

      - name: Pip Install
        run: python -m pip install --upgrade pip

      - name: Poetry Install
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true --local
          poetry install

      - name: Install Pyinstaller
        run: poetry add pyinstaller

      - name: Create Executable File (macOS 12)
        run: poetry run pyinstaller -F "main.py" --clean --dist ./out --name "CxKitty" --add-data ".venv/lib/python3.10/site-packages/ddddocr/common.onnx:ddddocr" --add-data ".venv/lib/python3.10/site-packages/ddddocr/common_det.onnx:ddddocr" --add-data ".venv/lib/python3.10/site-packages/ddddocr/common_old.onnx:ddddocr"

      - name: Copy Required Files
        run: |
          cp config.yml out/
          cp pyproject.toml out/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: CxKitty For macOS 12
          path: |
            out

  build-macos-latest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew install gettext
          echo "export PATH=\"/usr/local/opt/gettext/bin:$PATH\"" >> ~/.zshrc
          echo "export DYLD_LIBRARY_PATH=\"/usr/local/opt/gettext/lib:$DYLD_LIBRARY_PATH\"" >> ~/.zshrc
          source ~/.zshrc
          echo "Dependencies installed."

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'

      - name: Pip Install
        run: python -m pip install --upgrade pip

      - name: Poetry Install
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true --local
          poetry install

      - name: Install Pyinstaller
        run: poetry add pyinstaller

      - name: Create Executable File (macOS Latest)
        run: poetry run pyinstaller -F "main.py" --clean --dist ./out --name "CxKitty" --add-data ".venv/lib/python3.10/site-packages/ddddocr/common.onnx:ddddocr" --add-data ".venv/lib/python3.10/site-packages/ddddocr/common_det.onnx:ddddocr" --add-data ".venv/lib/python3.10/site-packages/ddddocr/common_old.onnx:ddddocr"

      - name: Copy Required Files
        run: |
          cp config.yml out/
          cp pyproject.toml out/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: CxKitty For macOS Latest
          path: |
            out
